#ifndef CONSTANTS_H_INCLUDED
#define CONSTANTS_H_INCLUDED

#define RACCOON_WIDTH 117
#define RACCOON_HEIGHT 85
#define RACCON_SPRITES 4

#define DOG_HEIGHT 122
#define DOG_WIDTH 161.2
#define DOG_SPRITES 10

#define LIVES 3

#endif // CONSTANTS_H_INCLUDED
